name: Tourism Project Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:

  register-dataset:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas

      - name: Register Dataset
        run: |
          python tourism_project/model_building/data_register.py

      - name: Upload Dataset
        uses: actions/upload-artifact@v4
        with:
          name: tourism-data
          path: tourism_project/data/tourism.csv


  data-prep:
    needs: register-dataset
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas scikit-learn

      - name: Download Dataset
        uses: actions/download-artifact@v4
        with:
          name: tourism-data
          path: tourism_project/data

      - name: Data Preparation
        run: |
          python tourism_project/model_building/prep.py

      - name: Upload Train/Test Files
        uses: actions/upload-artifact@v4
        with:
          name: train-test-data
          path: |
            Xtrain.csv
            Xtest.csv
            ytrain.csv
            ytest.csv


  model-training:
    needs: data-prep
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r .github/requirements.txt

      - name: Download Train/Test Files
        uses: actions/download-artifact@v4
        with:
          name: train-test-data

      - name: Train Model
        run: |
          python tourism_project/model_building/train.py

      - name: Upload Model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: tourism_project/deployment/best_tourism_model.joblib

      - name: Commit trained model
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add tourism_project/deployment/best_tourism_model.joblib

          git commit -m "Update trained model [skip ci]" || echo "Nothing to commit"

          git push
